/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Hilos.Aliens;
import Hilos.Mover;
import Hilos.Tiempo;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Sony Vaio
 */
public class NuevaPartida extends javax.swing.JFrame {

    /**
     * Creates new form NuevaPartida
     */
    

    public NuevaPartida() {
        initComponents();
        this.setResizable(false);
        //jLabel4.setLocation(10, posx);
        this.setBounds(0, 0, 750, 800);
        this.setLocationRelativeTo(null);
        //d = new Dimension(750, 700);
        aliens = new ArrayList<JLabel>();
        aliens2 = new ArrayList<JLabel>();
        aliens3 = new ArrayList<JLabel>();
        aliens4 = new ArrayList<JLabel>();
        aliens5 = new ArrayList<JLabel>();

        aliens.add(alien00);
        aliens.add(alien10);
        aliens.add(alien20);
        aliens.add(alien30);
        aliens.add(alien40);
        aliens.add(alien50);
        aliens.add(alien60);
        aliens.add(alien70);

        aliens2.add(alien01);
        aliens2.add(alien11);
        aliens2.add(alien21);
        aliens2.add(alien31);
        aliens2.add(alien41);
        aliens2.add(alien51);
        aliens2.add(alien61);
        aliens2.add(alien71);

        aliens3.add(alien02);
        aliens3.add(alien12);
        aliens3.add(alien22);
        aliens3.add(alien32);
        aliens3.add(alien42);
        aliens3.add(alien52);
        aliens3.add(alien62);
        aliens3.add(alien72);

        aliens4.add(alien03);
        aliens4.add(alien13);
        aliens4.add(alien23);
        aliens4.add(alien33);
        aliens4.add(alien43);
        aliens4.add(alien53);
        aliens4.add(alien63);
        aliens4.add(alien73);

        aliens5.add(alien04);
        aliens5.add(alien14);
        aliens5.add(alien24);
        aliens5.add(alien34);
        aliens5.add(alien44);
        aliens5.add(alien54);
        aliens5.add(alien64);
        aliens5.add(alien74);
        izq = new Aliens(aliens, 0);
        izq2 = new Aliens(aliens2, 60);
        izq3 = new Aliens(aliens3, 130);
        izq4 = new Aliens(aliens4, 200);
        izq5 = new Aliens(aliens5, 290);
        tim = new Tiempo(90,jLabel7);
        
        izq.start();
        
        izq2.start();
        izq3.start();
        izq4.start();
        izq5.start();
        //this.finaliza();
        this.moverNave();
        //tim.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelpuntos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        alien00 = new javax.swing.JLabel();
        alien10 = new javax.swing.JLabel();
        alien20 = new javax.swing.JLabel();
        alien30 = new javax.swing.JLabel();
        alien40 = new javax.swing.JLabel();
        alien50 = new javax.swing.JLabel();
        alien60 = new javax.swing.JLabel();
        alien70 = new javax.swing.JLabel();
        alien01 = new javax.swing.JLabel();
        alien11 = new javax.swing.JLabel();
        alien21 = new javax.swing.JLabel();
        alien41 = new javax.swing.JLabel();
        alien31 = new javax.swing.JLabel();
        alien51 = new javax.swing.JLabel();
        alien61 = new javax.swing.JLabel();
        alien71 = new javax.swing.JLabel();
        alien02 = new javax.swing.JLabel();
        alien12 = new javax.swing.JLabel();
        alien22 = new javax.swing.JLabel();
        alien32 = new javax.swing.JLabel();
        alien42 = new javax.swing.JLabel();
        alien52 = new javax.swing.JLabel();
        alien62 = new javax.swing.JLabel();
        alien72 = new javax.swing.JLabel();
        alien03 = new javax.swing.JLabel();
        alien23 = new javax.swing.JLabel();
        alien13 = new javax.swing.JLabel();
        alien33 = new javax.swing.JLabel();
        alien43 = new javax.swing.JLabel();
        alien53 = new javax.swing.JLabel();
        alien63 = new javax.swing.JLabel();
        alien73 = new javax.swing.JLabel();
        alien74 = new javax.swing.JLabel();
        alien64 = new javax.swing.JLabel();
        alien54 = new javax.swing.JLabel();
        alien44 = new javax.swing.JLabel();
        alien34 = new javax.swing.JLabel();
        alien24 = new javax.swing.JLabel();
        alien14 = new javax.swing.JLabel();
        alien04 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Puntos");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Velocidad");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tiempo");

        labelpuntos.setText("0");

        jLabel6.setText("x1");

        jLabel7.setText("0 s");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelpuntos)
                        .addGap(19, 19, 19)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(70, 70, 70)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelpuntos)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/nav.png"))); // NOI18N

        alien00.setForeground(new java.awt.Color(0, 0, 0));
        alien00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien1.png"))); // NOI18N
        alien00.setText("2");

        alien10.setForeground(new java.awt.Color(0, 0, 0));
        alien10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien1.png"))); // NOI18N
        alien10.setText("2");

        alien20.setForeground(new java.awt.Color(0, 0, 0));
        alien20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien1.png"))); // NOI18N
        alien20.setText("2");

        alien30.setForeground(new java.awt.Color(0, 0, 0));
        alien30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien1.png"))); // NOI18N
        alien30.setText("2");

        alien40.setForeground(new java.awt.Color(0, 0, 0));
        alien40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien1.png"))); // NOI18N
        alien40.setText("2");

        alien50.setForeground(new java.awt.Color(0, 0, 0));
        alien50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien1.png"))); // NOI18N
        alien50.setText("2");

        alien60.setForeground(new java.awt.Color(0, 0, 0));
        alien60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien1.png"))); // NOI18N
        alien60.setText("2");

        alien70.setForeground(new java.awt.Color(0, 0, 0));
        alien70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien1.png"))); // NOI18N
        alien70.setText("2");

        alien01.setForeground(new java.awt.Color(0, 0, 0));
        alien01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien01.setText("3");

        alien11.setForeground(new java.awt.Color(0, 0, 0));
        alien11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien11.setText("3");

        alien21.setForeground(new java.awt.Color(0, 0, 0));
        alien21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien21.setText("3");

        alien41.setForeground(new java.awt.Color(0, 0, 0));
        alien41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien41.setText("3");

        alien31.setForeground(new java.awt.Color(0, 0, 0));
        alien31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien31.setText("3");

        alien51.setForeground(new java.awt.Color(0, 0, 0));
        alien51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien51.setText("3");

        alien61.setForeground(new java.awt.Color(0, 0, 0));
        alien61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien61.setText("3");

        alien71.setForeground(new java.awt.Color(0, 0, 0));
        alien71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien71.setText("3");

        alien02.setForeground(new java.awt.Color(0, 0, 0));
        alien02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien02.setText("3");

        alien12.setForeground(new java.awt.Color(0, 0, 0));
        alien12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien12.setText("3");

        alien22.setForeground(new java.awt.Color(0, 0, 0));
        alien22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien22.setText("3");

        alien32.setForeground(new java.awt.Color(0, 0, 0));
        alien32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien32.setText("3");

        alien42.setForeground(new java.awt.Color(0, 0, 0));
        alien42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien42.setText("3");

        alien52.setForeground(new java.awt.Color(0, 0, 0));
        alien52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien52.setText("3");

        alien62.setForeground(new java.awt.Color(0, 0, 0));
        alien62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien62.setText("3");

        alien72.setForeground(new java.awt.Color(0, 0, 0));
        alien72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien2.png"))); // NOI18N
        alien72.setText("3");

        alien03.setForeground(new java.awt.Color(0, 0, 0));
        alien03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien03.setText("4");

        alien23.setForeground(new java.awt.Color(0, 0, 0));
        alien23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien23.setText("4");

        alien13.setForeground(new java.awt.Color(0, 0, 0));
        alien13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien13.setText("4");

        alien33.setForeground(new java.awt.Color(0, 0, 0));
        alien33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien33.setText("4");

        alien43.setForeground(new java.awt.Color(0, 0, 0));
        alien43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien43.setText("4");

        alien53.setForeground(new java.awt.Color(0, 0, 0));
        alien53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien53.setText("4");

        alien63.setForeground(new java.awt.Color(0, 0, 0));
        alien63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien63.setText("4");

        alien73.setForeground(new java.awt.Color(0, 0, 0));
        alien73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien73.setText("4");

        alien74.setForeground(new java.awt.Color(0, 0, 0));
        alien74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien74.setText("4");

        alien64.setForeground(new java.awt.Color(0, 0, 0));
        alien64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien64.setText("4");

        alien54.setForeground(new java.awt.Color(0, 0, 0));
        alien54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien54.setText("4");

        alien44.setForeground(new java.awt.Color(0, 0, 0));
        alien44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien44.setText("4");

        alien34.setForeground(new java.awt.Color(0, 0, 0));
        alien34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien34.setText("4");

        alien24.setForeground(new java.awt.Color(0, 0, 0));
        alien24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien24.setText("4");

        alien14.setForeground(new java.awt.Color(0, 0, 0));
        alien14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien14.setText("4");

        alien04.setForeground(new java.awt.Color(0, 0, 0));
        alien04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/alien3.png"))); // NOI18N
        alien04.setText("4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alien00, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alien10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alien20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alien50, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alien60, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alien70, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alien40, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alien30, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alien11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alien12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alien13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alien21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alien22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alien23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alien41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alien42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alien43))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alien31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alien32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alien33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alien51)
                            .addComponent(alien61))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alien62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alien63))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(alien52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alien53))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alien01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alien02)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alien03))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alien71)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alien72)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alien73)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alien14)
                    .addComponent(alien24)
                    .addComponent(alien44)
                    .addComponent(alien34)
                    .addComponent(alien64)
                    .addComponent(alien54)
                    .addComponent(alien04)
                    .addComponent(alien74))
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alien00)
                            .addComponent(alien01)
                            .addComponent(alien02)
                            .addComponent(alien03, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alien04, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(alien10)
                                .addComponent(alien11)
                                .addComponent(alien12)
                                .addComponent(alien13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(alien14, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(alien20))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alien21)
                            .addComponent(alien22)
                            .addComponent(alien23, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alien24, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(alien30)
                                    .addComponent(alien31)
                                    .addComponent(alien32)
                                    .addComponent(alien33)
                                    .addComponent(alien34))
                                .addGap(21, 21, 21)
                                .addComponent(alien40))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(alien41)
                                    .addComponent(alien42)
                                    .addComponent(alien43)
                                    .addComponent(alien44))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alien50)
                            .addComponent(alien51)
                            .addComponent(alien52)
                            .addComponent(alien53)
                            .addComponent(alien54))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alien60)
                            .addComponent(alien61)
                            .addComponent(alien62)
                            .addComponent(alien63)
                            .addComponent(alien64))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alien72)
                            .addComponent(alien71)
                            .addComponent(alien70)
                            .addComponent(alien73)
                            .addComponent(alien74))))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new NuevaPartida().setVisible(true);
                               //Thread hilo1 = new Thread(new Mover());
                //hilo1.start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alien00;
    private javax.swing.JLabel alien01;
    private javax.swing.JLabel alien02;
    private javax.swing.JLabel alien03;
    private javax.swing.JLabel alien04;
    private javax.swing.JLabel alien10;
    private javax.swing.JLabel alien11;
    private javax.swing.JLabel alien12;
    private javax.swing.JLabel alien13;
    private javax.swing.JLabel alien14;
    private javax.swing.JLabel alien20;
    private javax.swing.JLabel alien21;
    private javax.swing.JLabel alien22;
    private javax.swing.JLabel alien23;
    private javax.swing.JLabel alien24;
    private javax.swing.JLabel alien30;
    private javax.swing.JLabel alien31;
    private javax.swing.JLabel alien32;
    private javax.swing.JLabel alien33;
    private javax.swing.JLabel alien34;
    private javax.swing.JLabel alien40;
    private javax.swing.JLabel alien41;
    private javax.swing.JLabel alien42;
    private javax.swing.JLabel alien43;
    private javax.swing.JLabel alien44;
    private javax.swing.JLabel alien50;
    private javax.swing.JLabel alien51;
    private javax.swing.JLabel alien52;
    private javax.swing.JLabel alien53;
    private javax.swing.JLabel alien54;
    private javax.swing.JLabel alien60;
    private javax.swing.JLabel alien61;
    private javax.swing.JLabel alien62;
    private javax.swing.JLabel alien63;
    private javax.swing.JLabel alien64;
    private javax.swing.JLabel alien70;
    private javax.swing.JLabel alien71;
    private javax.swing.JLabel alien72;
    private javax.swing.JLabel alien73;
    private javax.swing.JLabel alien74;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelpuntos;
    // End of variables declaration//GEN-END:variables
    private Dimension d;
    private JLabel bala;
    public int posx = 100, posy = 0, puntos = 0, cambio = 0, cambio2 = 9;
    private ArrayList<Thread> hil = new ArrayList<Thread>();
    private ArrayList<JLabel> aliens;
    private ArrayList<JLabel> aliens2;
    private ArrayList<JLabel> aliens3, aliens4, aliens5;
    private Mover hiloBala;
    private Aliens izq, izq2, izq3, izq4, izq5;
    private Tiempo tim;
    private boolean pausa=false;

    public void moverNave() {
        KeyListener k = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent ke) {

            }

            @Override
            public void keyPressed(KeyEvent ke) {
                if (pausa==false){
                if (ke.getKeyCode() == 40) {
                    if (posx < 600) {
                        posx += 5;
                    }
                    jLabel4.setLocation(10, posx);
                    // System.out.println("Abajo");
                }
                if (ke.getKeyCode() == 38) {
                    if (posx > 70) {
                        posx -= 5;
                    }
                    jLabel4.setLocation(10, posx);

                    //System.out.println("Arriba");
                }
                if (ke.getKeyCode() == 32) {

                    bala = new JLabel();
                    bala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/bala.png")));
                    //System.out.println("Posicion nave:" + jLabel4.getY());
                    bala.setBounds(20, jLabel4.getY(), 100, 50);
                    jPanel1.add(bala);
                    //System.out.println("Posicion alien:" + alien00.getX() + "," + alien00.getY());

                    if (cambio < 8) {
                        cambio = maspuntos(aliens,aliens2,aliens3,aliens4,aliens5);
                        //System.out.println(maspuntos(aliens,aliens2,aliens3,aliens4,aliens5));
                        hiloBala = new Mover(bala, jLabel4.getY(), jPanel1, jLabel4, aliens, puntos, labelpuntos);
                        hiloBala.start();
                        hil.add(hiloBala);
                    } else if (cambio>7 && cambio<16){
                        cambio = maspuntos(aliens,aliens2,aliens3,aliens4,aliens5);
                        //System.out.println("Cambio en else if:" +cambio);
                        hiloBala = new Mover(bala, jLabel4.getY(), jPanel1, jLabel4, aliens2, puntos, labelpuntos);
                        hiloBala.start();
                    }else if (cambio>15 && cambio<24){
                        cambio = maspuntos(aliens,aliens2,aliens3,aliens4,aliens5);
                        //System.out.println("Cambio en else if2:" +cambio);
                        hiloBala = new Mover(bala, jLabel4.getY(), jPanel1, jLabel4, aliens3, puntos, labelpuntos);
                        hiloBala.start();
                        hil.add(hiloBala);
                    }else if (cambio>23 && cambio<32){
                        cambio = maspuntos(aliens,aliens2,aliens3,aliens4,aliens5);
                        //System.out.println("Cambio en else if2:" +cambio);
                        hiloBala = new Mover(bala, jLabel4.getY(), jPanel1, jLabel4, aliens4, puntos, labelpuntos);
                        hiloBala.start();
                        hil.add(hiloBala);
                    }
                    else if (cambio>31 && cambio<40){
                        cambio = maspuntos(aliens,aliens2,aliens3,aliens4,aliens5);
                        //System.out.println("Cambio en else if2:" +cambio);
                        hiloBala = new Mover(bala, jLabel4.getY(), jPanel1, jLabel4, aliens5, puntos, labelpuntos);
                        hiloBala.start();
                        hil.add(hiloBala);
                    }
                }}
                if (ke.getKeyCode() == 27) {
                    pausa = true;
                    //System.out.println(hil.size());
                    for (int i = 0; i < hil.size(); i++) {
                       // System.out.println(hil.get(i));
                        hil.get(i).suspend();
                    }
                    izq.suspend();
                    izq2.suspend();
                    izq3.suspend();
                    izq4.suspend();
                    izq5.suspend();
                    tim.suspend();
                    String[] os = {"Sí","No"};
                    int op = JOptionPane.showOptionDialog(null, "¿Desea continuar?", "Pausa", 0, JOptionPane.QUESTION_MESSAGE,null, os, "");
                    if (op == 1){
                        dispose();
                    }else{
                    pausa = false;
                    //System.out.println(hil.size());
                    for (int i = 0; i < hil.size(); i++) {
                        //System.out.println(hil.get(i));
                        hil.get(i).resume();
                    }
                    izq.resume();
                    izq2.resume();
                    izq3.resume();
                    izq4.resume();
                    izq5.resume();
                    tim.resume();
                    }
                }
            }

            @Override
            public void keyReleased(KeyEvent ke) {

            }
        };
        addKeyListener(k);
    }


    public int maspuntos(ArrayList<JLabel> aliens, ArrayList<JLabel> aliens2, ArrayList<JLabel> aliens3, ArrayList<JLabel> aliens4, ArrayList<JLabel> aliens5) {
        int puntos=0;
        int muertes = 0;
        for (int i = 0; i < aliens.size(); i++) {
            if (aliens.get(i).isEnabled() == false) {
                puntos+=10;
                muertes++;
            }
        }
        for (int i = 0; i < aliens2.size(); i++) {
            if (aliens2.get(i).isEnabled() == false) {
                puntos+=20;
                muertes++;
            }
        }
         for (int i = 0; i < aliens3.size(); i++) {
            if (aliens3.get(i).isEnabled() == false) {
                puntos+=20;
                muertes++;
            }
        }for (int i = 0; i < aliens4.size(); i++) {
            if (aliens4.get(i).isEnabled() == false) {
                puntos+=30;
                muertes++;
            }
        }for (int i = 0; i < aliens5.size(); i++) {
            if (aliens5.get(i).isEnabled() == false) {
                puntos+=30;
                muertes++;
            }
        }
        labelpuntos.setText(puntos+"");
        //System.out.println(izq.isAlive());
        return muertes;
    }

   
}
